<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

        <div class="item active">
            <img src="images/slide1.jpg">
            <div class="carousel-caption">
                <heading>Edwardes Boys Hostel</heading>
                <p>A Beautiful view of Edwardes College Boys Hostel</p>
            </div>
        </div>

        <div class="item">
            <img src="images/slide2.jpg">
            <div class="carousel-caption">
                <heading><subtitle>Senior Hostels</subtitle></heading>
            </div>
        </div>

        <div class="item">
            <img src="images/slide3.jpg">
            <div class="carousel-caption">
                <heading>Jesper Moller Sorensen</heading>
                <p>Ambassador of Denmark in Pakistan Visits Edwardes College 2014</p>
            </div>
        </div>

        <div class="item">
            <img src="images/slide4.jpg">
            <div class="carousel-caption">
                <heading>Old Hall</heading>
                <p>This Department have a Old Hall and A-Levels</p>
            </div>
        </div>

        <div class="item">
            <img src="images/slide5.jpg">
            <div class="carousel-caption">
                <heading>Oxford University Gift</heading>
                <p>This Building is Gift for Edwardes College, from Oxford University 1900</p>

            </div>
        </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>